version: "3"
services:
    blogdbd:
            container_name: blogdb
            image: mariadb
            ports:
                - "18766:3306"
            volumes: 
                - blog_data:/var/lib/mysql
            environment: 
                MYSQL_ROOT_PASSWORD: admin
                MYSQL_DATABASE: wordpress_db
        
    blogapp:
            container_name: blogapp
            image: wordpress
            ports:
                - "5000:80"
            volumes: 
                - blog_app:/var/www/html
            environment: 
                WORDPRESS_DB_HOST: 'blogdbd:3306'
                WORDPRESS_DB_PASSWORD: admin
            depends_on:
                - blogdbd
            links:
                - blogdbd
volumes: 
    blog_data:
    blog_app: